### PR TITLE
fix: fix broker registration for bootstrapped resources

### LINKED ISSUE #577: Broker registration fails for bootstrapped resources
**Describe the bug**
Registering a resource that has been created by bootstrapping fails with the following error:

```
{
  "reason": {
    "properties": null,
    "@id": "https://w3id.org/idsa/code/INTERNAL_RECIPIENT_ERROR"
  },
  "payload": "500 - Server Error",
  "type": "de.fraunhofer.iais.eis.RejectionMessageImpl"
}
```

This is not the case for resources that have been created via the API endpoints.

Some values are also doubled in the bootstrapped entities, e.g. checkSum for artifact.

**To Reproduce**
1. Checkout *main* branch as is.
2. Set bootstrap.enabled to true in application properties.
3. Start the connector.
4. See log message: *An error occurred while registering resources at the broker.*
5. Try to register one of the resources created by bootstrapping at broker manually via */api/ids/resource/update*
6. See above mentioned error as response.

**Expected behavior**
Registration of bootstrapped resources should complete without error.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version (DSC): 6.2.0

### PR DESCRIPTION
**Pull request by ronjaquensel**
Closes #577

### CODE REVIEW

File: src/main/java/io/dataspaceconnector/service/resource/ids/builder/IdsResourceBuilder.java [hunk 1]
```diff
@@ -128,4 +147,16 @@
...
+    /**
+     * Returns the language code for a language, so e.g. "EN" for the language with ID
+     * "https://w3id.org/idsa/code/EN".
+     *
+     * @param language the language object.
+     * @return the corresponding language code.
+     */
+    private String getLanguageCode(final Language language) {
+        final var languageId = language.getId().toString();
+        return languageId.substring(languageId.length() - 2);
```
Comment (ghost) [inline src/main/java/io/dataspaceconnector/service/resource/ids/builder/IdsResourceBuilder.java]: could break for following, is however a special case:
https://github.com/International-Data-Spaces-Association/InformationModel/blob/9afd5b4c0bfa5db46793c33aefff81a6a8e304ab/codes/Language.ttl#L12

Comment (ronjaquensel) [reply src/main/java/io/dataspaceconnector/service/resource/ids/builder/IdsResourceBuilder.java]: Thanks for pointing that out. Refactored it in the last commit to take everything after the last slash.

Comment (ghost) [reply src/main/java/io/dataspaceconnector/service/resource/ids/builder/IdsResourceBuilder.java]: Just a quick thought, wouldn't `return language.name()` do exactly the same?

**Review by brianjahnke — APPROVED** [review]
