### PR TITLE
fix: update an artifact

### LINKED ISSUE #670: Updating created Artifact results in TransientObjectException
When creating a new Artifact using `POST /api/artifacts` with example data:

```json
{
  "title": "string",
  "description": "string",
  "accessUrl": "https://string",
  "basicAuth": {
    "key": "string",
    "value": "string"
  },
  "apiKey": {
    "key": "string",
    "value": "string"
  },
  "value": "string",
  "automatedDownload": true
}
```

and then using `PUT /api/artifacts/{id}` where id is the id of the created Artifact, a `TransientObjectException` is thrown:

```
Caused by: org.hibernate.TransientObjectException: object references an unsaved transient instance - save the transient instance before flushing: io.dataspaceconnector.model.auth.Authentication
```

### PR DESCRIPTION
**Pull request by goekhanKahriman**

### CODE REVIEW

File: src/main/java/io/dataspaceconnector/model/artifact/RemoteData.java [hunk 1]
```diff
@@ -61,7 +62,7 @@
     /**
      * List of additional authentication elements.
      */
-    @OneToMany
+    @OneToMany(cascade = {CascadeType.ALL})
```
Comment (juliapampus) [inline src/main/java/io/dataspaceconnector/model/artifact/RemoteData.java:65]: Don't use cascading. Authentication has to be updated manually in the factory.

**Review by brianjahnke — DISMISSED** [review]

**Review by brianjahnke — DISMISSED** [review]

**Review by brianjahnke — DISMISSED** [review]

**Review by brianjahnke — DISMISSED** [review]

**Review by juliapampus — APPROVED** [review]
